version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        networks:
            main:
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        ports:
            - 80:80
            - 81:81
            - "443:443"
        depends_on:
            - php
            - mysql
    php:
        build: ./images/php
        restart: always
        container_name: php
        networks:
            main:
        volumes:
            - ./images/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./www:/var/www
            - ~/.local/share/fish:/home/meido/.local/share/fish
            - ~/.config/fish:/home/meido/.config/fish
            - ~/.git-credentials:/home/meido/.git-credentials
    php8:
        build: ./images/php8
        restart: always
        container_name: php8
        networks:
            main:
        volumes:
            - ./images/php8/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./images/php8/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./www:/var/www
            - ~/.local/share/fish:/home/meido/.local/share/fish
            - ~/.config/fish:/home/meido/.config/fish
            - ~/.git-credentials:/home/meido/.git-credentials
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        networks:
            main:
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./db/initdb/:/docker-entrypoint-initdb.d/
            - ./db/mysql:/var/lib/mysql
            - ./db/dumps:/dumps
            - ./logs:/var/log/mysql/
    node:
        image: node:14.18.3-alpine3.15
        container_name: node
        networks:
            main:
        working_dir: /app
        stdin_open: true
        mem_limit: 2048m
        ports:
            - 3000:3000
        volumes:
            - ./frontends/elya-frontend/:/app/ #zazajobs-admin
        command: sh -c "yarn install && yarn run serve"
    clickhouse:
        image: yandex/clickhouse-server:21.3.20.1
        container_name: clickhouse
        networks:
            main:
        mem_limit: 1024m
        ports:
            - 8123:8123
        volumes:
            - ./db/clickhouse:/var/lib/clickhouse
    postgres:
        image: postgres
        container_name: postgres
        networks:
            main:
        environment:
            POSTGRES_DB: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./db/postregs:/var/lib/postgresql
            - ./db/dumps:/dumps
            - ./logs:/var/log/postgresql/
        ports:
        - "5432:5432"
    # redis:
    #     image: redis
    #     container_name: redis
    #     restart: always
    #     mem_limit: 1024m
    #     ports:
    #         - 6379:6379
    #     command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]
    # echo-server:
    #     image: oanhnn/laravel-echo-server
    #     container_name: echo-server
    #     mem_limit: 512m
    #     environment:
    #         REDIS_HOST: ${REDIS_HOST}
    #         REDIS_PORT: ${REDIS_PORT}
    #         REDIS_PREFIX: ${REDIS_PREFIX}
    #         REDIS_PASSWORD: ${REDIS_PASSWORD}
    #         REDIS_DB: ${REDIS_DB}
    #     volumes:
    #         - ./config/echo_server/laravel-echo-server.json:/app/laravel-echo-server.json
    #     ports:
    #         - 6001:6001

networks:
    main:
        external: True