version: '3'
services:
    nginx:
        image: nginx
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        ports:
            - 80:80
            - "443:443"
        restart: always
        depends_on:
            - php
            - postgres
            - mysql
    php:
        build: ./images/php
        restart: always
        volumes:
            - ./images/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./www:/var/www
            - ~/.local/share/fish:/home/user/.local/share/fish
            - ~/.config/fish:/home/user/.config/fish
            - ~/.git-credentials:/home/user/.git-credentials
            - ~/.gitconfig:/home/user/.gitconfig
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./db/initdb/:/docker-entrypoint-initdb.d/
            - ./db/data/:/var/lib/postgresql/data
            - ./logs:/var/log/postgresql/
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - postgres
            - mysql
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./db/initdb/:/docker-entrypoint-initdb.d/
            - ./db/mysql:/var/lib/mysql
            - ./logs:/var/log/mysql/