version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        ports:
            - 80:80
            - "443:443"
        restart: always
        depends_on:
            - php
            - mysql
    php:
        build: ./images/php
        restart: always
        container_name: php
        volumes:
            - ./images/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./www:/var/www
            - ~/.local/share/fish:/home/meido/.local/share/fish
            - ~/.config/fish:/home/meido/.config/fish
            - ~/.git-credentials:/home/meido/.git-credentials
    # postgres:
    #     image: postgres
    #     restart: always
    #     environment:
    #         POSTGRES_DB: ${DB_NAME}
    #         POSTGRES_USER: ${DB_USER}
    #         POSTGRES_PASSWORD: ${DB_PASSWORD}
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - ./db/initdb/:/docker-entrypoint-initdb.d/
    #         - ./db/data/:/var/lib/postgresql/data
    #         - ./logs:/var/log/postgresql/
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - mysql
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql
        environment:
            MYSQL_DATABASE: smitup
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./db/initdb/:/docker-entrypoint-initdb.d/
            - ./db/mysql:/var/lib/mysql
            - ./db/dumps:/dumps
            - ./logs:/var/log/mysql/
    node:
        image: node:14.18.3-alpine3.15
        container_name: node
        restart: always
        working_dir: /app
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend/:/app/
        command: sh -c "yarn install && yarn run serve"
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]
    echo-server:
        image: oanhnn/laravel-echo-server
        container_name: echo-server
        environment:
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PREFIX: ${REDIS_PREFIX}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_DB: ${REDIS_DB}
        volumes:
            - ./config/echo_server/laravel-echo-server.json:/app/laravel-echo-server.json
        ports:
            - 6001:6001

